"""
Tests for Pydantic schemas validation.
"""

import pytest
from pydantic import ValidationError

from ksb_report.schemas import (
    FooterConfig,
    HeaderConfig,
    HeaderLine,
    MarginsConfig,
    PageConfig,
    ReportTemplate,
    TableElement,
    TextElement,
)


class TestReportTemplate:
    """Test ReportTemplate validation."""

    def test_minimal_template(self):
        """A template with no elements should be valid."""
        t = ReportTemplate()
        assert t.page.orientation == "portrait"
        assert t.page.format == "A4"
        assert t.elements == []
        assert t.title is None

    def test_template_with_title(self):
        t = ReportTemplate(title="Test Report", title_font_size=18)
        assert t.title == "Test Report"
        assert t.title_font_size == 18

    def test_template_with_elements(self):
        t = ReportTemplate(
            elements=[
                {"type": "text", "content": "Hello World"},
                {
                    "type": "table",
                    "headers": ["A", "B"],
                    "rows": [["1", "2"]],
                },
            ]
        )
        assert len(t.elements) == 2
        assert isinstance(t.elements[0], TextElement)
        assert isinstance(t.elements[1], TableElement)

    def test_template_with_header(self):
        t = ReportTemplate(
            header={
                "lines": [
                    {"text": "Company Name", "font_size": 16, "bold": True},
                    {"text": "Subtitle", "italic": True},
                ]
            }
        )
        assert t.header is not None
        assert len(t.header.lines) == 2
        assert t.header.lines[0].bold is True

    def test_template_with_footer(self):
        t = ReportTemplate(
            footer={
                "left_text": "Generated by KSB-Report",
                "show_date": True,
            }
        )
        assert t.footer is not None
        assert t.footer.left_text == "Generated by KSB-Report"

    def test_landscape_orientation(self):
        t = ReportTemplate(page={"orientation": "landscape"})
        assert t.page.orientation == "landscape"

    def test_invalid_orientation(self):
        with pytest.raises(ValidationError):
            ReportTemplate(page={"orientation": "diagonal"})

    def test_custom_margins(self):
        t = ReportTemplate(
            page={"margins": {"top": 20, "bottom": 20, "left": 15, "right": 15}}
        )
        assert t.page.margins.top == 20
        assert t.page.margins.left == 15

    def test_metadata(self):
        t = ReportTemplate(metadata={"author": "John Doe", "filename": "test.pdf"})
        assert t.metadata["author"] == "John Doe"


class TestTableElement:
    """Test TableElement validation."""

    def test_basic_table(self):
        t = TableElement(
            headers=["Name", "Age"],
            rows=[["Alice", "30"], ["Bob", "25"]],
        )
        assert len(t.headers) == 2
        assert len(t.rows) == 2

    def test_table_with_colors(self):
        t = TableElement(
            headers=["A"],
            rows=[["1"]],
            header_bg_color=(255, 0, 0),
            header_text_color=(255, 255, 255),
        )
        assert t.header_bg_color == (255, 0, 0)

    def test_table_with_max_rows(self):
        t = TableElement(
            headers=["A"],
            rows=[["1"]],
            max_rows_per_page=20,
        )
        assert t.max_rows_per_page == 20


class TestTextElement:
    """Test TextElement validation."""

    def test_basic_text(self):
        t = TextElement(content="Hello")
        assert t.content == "Hello"
        assert t.font_size == 11
        assert t.font_style == ""
        assert t.align == "L"

    def test_styled_text(self):
        t = TextElement(content="Bold", font_style="B", align="C", font_size=14)
        assert t.font_style == "B"
        assert t.align == "C"

    def test_invalid_font_style(self):
        with pytest.raises(ValidationError):
            TextElement(content="Bad", font_style="X")


class TestHeaderConfig:
    """Test HeaderConfig validation."""

    def test_default_header(self):
        h = HeaderConfig()
        assert h.enabled is True
        assert h.separator_line is True
        assert h.lines == []

    def test_header_with_logos(self):
        h = HeaderConfig(
            logo_left="/path/to/left.png",
            logo_right="/path/to/right.png",
            logo_width=25,
        )
        assert h.logo_left == "/path/to/left.png"
        assert h.logo_width == 25
