"""
Tests for Pydantic schemas validation.
"""

import pytest
from pydantic import ValidationError

from ksb_report.schemas import (
    BoxElement,
    ColumnDef,
    ColumnsElement,
    FooterConfig,
    HeaderConfig,
    HeaderLine,
    ListElement,
    MarginsConfig,
    PageBreakElement,
    PageConfig,
    QRCodeElement,
    ReportTemplate,
    SectionTitleElement,
    SeparatorElement,
    SignatureBlockElement,
    SignatureEntry,
    StyleDef,
    TableElement,
    TextElement,
    WatermarkConfig,
)


class TestReportTemplate:
    """Test ReportTemplate validation."""

    def test_minimal_template(self):
        t = ReportTemplate()
        assert t.page.orientation == "portrait"
        assert t.page.format == "A4"
        assert t.elements == []
        assert t.title is None

    def test_template_with_title(self):
        t = ReportTemplate(title="Test Report", title_font_size=18)
        assert t.title == "Test Report"
        assert t.title_font_size == 18

    def test_template_with_elements(self):
        t = ReportTemplate(
            elements=[
                {"type": "text", "content": "Hello World"},
                {"type": "table", "headers": ["A", "B"], "rows": [["1", "2"]]},
            ]
        )
        assert len(t.elements) == 2
        assert isinstance(t.elements[0], TextElement)
        assert isinstance(t.elements[1], TableElement)

    def test_template_with_header(self):
        t = ReportTemplate(
            header={
                "lines": [
                    {"text": "Company Name", "font_size": 16, "bold": True},
                    {"text": "Subtitle", "italic": True},
                ]
            }
        )
        assert t.header is not None
        assert len(t.header.lines) == 2

    def test_template_with_footer(self):
        t = ReportTemplate(
            footer={"left_text": "Generated by KSB-Report", "show_date": True}
        )
        assert t.footer is not None
        assert t.footer.left_text == "Generated by KSB-Report"

    def test_landscape_orientation(self):
        t = ReportTemplate(page={"orientation": "landscape"})
        assert t.page.orientation == "landscape"

    def test_invalid_orientation(self):
        with pytest.raises(ValidationError):
            ReportTemplate(page={"orientation": "diagonal"})

    def test_custom_margins(self):
        t = ReportTemplate(
            page={"margins": {"top": 20, "bottom": 20, "left": 15, "right": 15}}
        )
        assert t.page.margins.top == 20

    def test_metadata(self):
        t = ReportTemplate(metadata={"author": "John", "filename": "test.pdf"})
        assert t.metadata["author"] == "John"

    def test_watermark(self):
        t = ReportTemplate(watermark={"text": "DRAFT", "font_size": 50})
        assert t.watermark is not None
        assert t.watermark.text == "DRAFT"

    def test_variables(self):
        t = ReportTemplate(
            variables={"company": "KSB Tech", "year": "2026"},
        )
        assert t.variables["company"] == "KSB Tech"

    def test_styles(self):
        t = ReportTemplate(
            styles={
                "title": {"font_size": 16, "font_style": "B", "align": "C"},
                "body": {"font_size": 11},
            },
        )
        assert t.styles["title"].font_size == 16
        assert t.styles["body"].font_style is None


class TestNewElements:
    """Test new element types."""

    def test_page_break(self):
        t = ReportTemplate(elements=[{"type": "page_break"}])
        assert isinstance(t.elements[0], PageBreakElement)

    def test_separator(self):
        t = ReportTemplate(
            elements=[{"type": "separator", "color": [255, 0, 0], "thickness": 1.0}]
        )
        el = t.elements[0]
        assert isinstance(el, SeparatorElement)
        assert el.color == (255, 0, 0)
        assert el.thickness == 1.0

    def test_separator_defaults(self):
        el = SeparatorElement()
        assert el.color == (200, 200, 200)
        assert el.width_percent == 100

    def test_list_bullet(self):
        t = ReportTemplate(
            elements=[
                {"type": "list", "items": ["A", "B", "C"], "list_style": "bullet"}
            ]
        )
        el = t.elements[0]
        assert isinstance(el, ListElement)
        assert len(el.items) == 3

    def test_list_numbered(self):
        el = ListElement(items=["First", "Second"], list_style="numbered")
        assert el.list_style == "numbered"

    def test_list_dash(self):
        el = ListElement(items=["X"], list_style="dash")
        assert el.list_style == "dash"

    def test_box(self):
        t = ReportTemplate(
            elements=[
                {
                    "type": "box",
                    "border_color": [255, 0, 0],
                    "bg_color": [255, 255, 230],
                    "padding": 8,
                    "elements": [
                        {"type": "text", "content": "Inside the box"},
                    ],
                }
            ]
        )
        el = t.elements[0]
        assert isinstance(el, BoxElement)
        assert len(el.elements) == 1
        assert isinstance(el.elements[0], TextElement)

    def test_qrcode(self):
        t = ReportTemplate(
            elements=[{"type": "qrcode", "data": "https://example.com", "size": 25}]
        )
        el = t.elements[0]
        assert isinstance(el, QRCodeElement)
        assert el.data == "https://example.com"

    def test_signature_block(self):
        t = ReportTemplate(
            elements=[
                {
                    "type": "signature_block",
                    "signatures": [
                        {"label": "Le Directeur", "name": "M. DUPONT"},
                        {"label": "Le Comptable", "name": "Mme. MARTIN"},
                    ],
                }
            ]
        )
        el = t.elements[0]
        assert isinstance(el, SignatureBlockElement)
        assert len(el.signatures) == 2
        assert el.signatures[0].name == "M. DUPONT"

    def test_columns(self):
        t = ReportTemplate(
            elements=[
                {
                    "type": "columns",
                    "columns": [
                        {
                            "width": 50,
                            "elements": [{"type": "text", "content": "Left"}],
                        },
                        {
                            "width": 50,
                            "elements": [{"type": "text", "content": "Right"}],
                        },
                    ],
                    "gap": 10,
                }
            ]
        )
        el = t.elements[0]
        assert isinstance(el, ColumnsElement)
        assert len(el.columns) == 2
        assert el.gap == 10

    def test_columns_nested_elements(self):
        """Columns can contain any element type."""
        t = ReportTemplate(
            elements=[
                {
                    "type": "columns",
                    "columns": [
                        {
                            "width": 60,
                            "elements": [
                                {"type": "section_title", "text": "Left Section"},
                                {"type": "text", "content": "Content"},
                            ],
                        },
                        {
                            "width": 40,
                            "elements": [
                                {"type": "list", "items": ["A", "B"]},
                            ],
                        },
                    ],
                }
            ]
        )
        assert isinstance(t.elements[0], ColumnsElement)
        col = t.elements[0]
        assert isinstance(col.columns[0].elements[0], SectionTitleElement)
        assert isinstance(col.columns[1].elements[0], ListElement)


class TestTableElement:
    """Test TableElement validation."""

    def test_basic_table(self):
        t = TableElement(headers=["Name", "Age"], rows=[["Alice", "30"], ["Bob", "25"]])
        assert len(t.headers) == 2

    def test_table_with_column_aligns(self):
        t = TableElement(
            headers=["Name", "Score", "Total"],
            rows=[["Alice", "95", "1000"]],
            column_aligns=["L", "C", "R"],
        )
        assert t.column_aligns == ["L", "C", "R"]

    def test_table_with_colors(self):
        t = TableElement(
            headers=["A"],
            rows=[["1"]],
            header_bg_color=(255, 0, 0),
        )
        assert t.header_bg_color == (255, 0, 0)


class TestTextElement:
    """Test TextElement validation."""

    def test_basic_text(self):
        t = TextElement(content="Hello")
        assert t.content == "Hello"
        assert t.font_size == 11

    def test_styled_text(self):
        t = TextElement(content="Bold", font_style="B", align="C", font_size=14)
        assert t.font_style == "B"

    def test_invalid_font_style(self):
        with pytest.raises(ValidationError):
            TextElement(content="Bad", font_style="X")

    def test_text_with_style_ref(self):
        t = TextElement(content="Styled", style="title")
        assert t.style == "title"


class TestHeaderConfig:
    """Test HeaderConfig validation."""

    def test_default_header(self):
        h = HeaderConfig()
        assert h.enabled is True
        assert h.separator_line is True

    def test_header_with_logos(self):
        h = HeaderConfig(logo_left="/path/to/left.png", logo_width=25)
        assert h.logo_left == "/path/to/left.png"


class TestInvalidElements:
    """Test that invalid element types are rejected."""

    def test_unknown_type(self):
        with pytest.raises(ValidationError):
            ReportTemplate(elements=[{"type": "nonexistent", "content": "bad"}])

    def test_missing_required_fields(self):
        with pytest.raises(ValidationError):
            ReportTemplate(elements=[{"type": "table"}])  # Missing headers/rows
