"""
Tests for ReportEngine — PDF generation.
"""

import pytest

from ksb_report.engine import ReportEngine
from ksb_report.schemas import (
    FooterConfig,
    HeaderConfig,
    HeaderLine,
    ReportTemplate,
)
from ksb_report.templates.invoice import invoice_template


class TestReportEngine:
    """Test PDF generation via ReportEngine."""

    def setup_method(self):
        self.engine = ReportEngine()

    def test_generate_empty_template(self):
        """An empty template should still produce a valid PDF."""
        template = ReportTemplate()
        pdf_bytes = self.engine.generate(template)
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_with_title(self):
        template = ReportTemplate(title="Test Report")
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_with_text_elements(self):
        template = ReportTemplate(
            title="Text Report",
            elements=[
                {"type": "text", "content": "Hello World", "font_size": 14},
                {"type": "text", "content": "Second paragraph", "font_style": "I"},
                {"type": "spacer", "height": 10},
                {"type": "text", "content": "After spacer", "align": "C"},
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"
        assert len(pdf_bytes) > 500

    def test_generate_with_table(self):
        template = ReportTemplate(
            title="Table Report",
            elements=[
                {
                    "type": "table",
                    "headers": ["Name", "Age", "City"],
                    "rows": [
                        ["Alice", "30", "Paris"],
                        ["Bob", "25", "London"],
                        ["Charlie", "35", "Berlin"],
                    ],
                    "header_bg_color": [41, 128, 185],
                },
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_with_large_table(self):
        """A table with many rows should produce multiple pages."""
        rows = [[f"Item {i}", f"Value {i}", f"Desc {i}"] for i in range(100)]
        template = ReportTemplate(
            title="Large Table",
            elements=[
                {
                    "type": "table",
                    "headers": ["Item", "Value", "Description"],
                    "rows": rows,
                    "max_rows_per_page": 25,
                },
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"
        assert len(pdf_bytes) > 2000

    def test_generate_with_section_title(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "section_title",
                    "text": "Section I",
                    "bg_color": [200, 200, 200],
                },
                {"type": "text", "content": "Section content here."},
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_with_key_value(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "key_value",
                    "pairs": [
                        ["Client", "John Doe"],
                        ["Date", "25/02/2026"],
                        ["Ref", "INV-001"],
                    ],
                },
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_with_header_and_footer(self):
        template = ReportTemplate(
            title="Full Report",
            header=HeaderConfig(
                lines=[
                    HeaderLine(text="My Company", font_size=16, bold=True),
                    HeaderLine(
                        text="Department of Engineering", font_size=10, italic=True
                    ),
                ],
                separator_line=True,
            ),
            footer=FooterConfig(
                left_text="Generated by KSB-Report",
                show_date=True,
            ),
            elements=[
                {"type": "text", "content": "This report has a header and footer."},
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_to_file(self, tmp_path):
        """Test saving PDF to disk."""
        template = ReportTemplate(title="File Output Test")
        output = str(tmp_path / "test_output.pdf")
        result = self.engine.generate_to_file(template, output)
        assert result == output
        with open(output, "rb") as f:
            data = f.read()
        assert data[:5] == b"%PDF-"

    def test_landscape_orientation(self):
        template = ReportTemplate(
            page={"orientation": "landscape"},
            title="Landscape Report",
            elements=[
                {"type": "text", "content": "Wide page content."},
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"

    def test_invoice_template_helper(self):
        """Test the pre-built invoice template."""
        template = invoice_template(
            company_name="KSB Tech",
            invoice_number="2026-001",
            client_name="Jean Dupont",
            client_address="123 Rue de Paris",
            items=[
                {"description": "Widget A", "quantity": 2, "unit_price": 15.00},
                {"description": "Service B", "quantity": 1, "unit_price": 50.00},
            ],
            tax_rate=0.18,
            notes="Merci pour votre confiance.",
        )
        assert template.title == "FACTURE 2026-001"
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"
        assert len(pdf_bytes) > 1000

    def test_mixed_content(self):
        """Test a report with all element types combined."""
        template = ReportTemplate(
            title="Mixed Content Report",
            header=HeaderConfig(
                lines=[HeaderLine(text="Test Corp", font_size=14, bold=True)],
            ),
            footer=FooterConfig(left_text="Test Footer"),
            elements=[
                {"type": "section_title", "text": "I. Introduction"},
                {"type": "text", "content": "This is the introduction."},
                {"type": "spacer", "height": 5},
                {"type": "key_value", "pairs": [["Key", "Value"], ["Date", "Today"]]},
                {"type": "spacer", "height": 5},
                {"type": "section_title", "text": "II. Data"},
                {
                    "type": "table",
                    "headers": ["Col A", "Col B"],
                    "rows": [["1", "2"], ["3", "4"]],
                },
                {
                    "type": "text",
                    "content": "Conclusion.",
                    "font_style": "B",
                    "align": "C",
                },
            ],
        )
        pdf_bytes = self.engine.generate(template)
        assert pdf_bytes[:5] == b"%PDF-"
        assert len(pdf_bytes) > 1000
