"""
Tests for ReportEngine — PDF generation with all element types.
"""

import pytest

from ksb_report.engine import ReportEngine
from ksb_report.schemas import (
    FooterConfig,
    HeaderConfig,
    HeaderLine,
    ReportTemplate,
    WatermarkConfig,
)
from ksb_report.templates.invoice import invoice_template


class TestReportEngine:
    """Test PDF generation via ReportEngine."""

    def setup_method(self):
        self.engine = ReportEngine()

    def _assert_valid_pdf(self, pdf_bytes):
        assert isinstance(pdf_bytes, bytes)
        assert len(pdf_bytes) > 0
        assert pdf_bytes[:5] == b"%PDF-"

    def test_generate_empty_template(self):
        self._assert_valid_pdf(self.engine.generate(ReportTemplate()))

    def test_generate_with_title(self):
        self._assert_valid_pdf(
            self.engine.generate(ReportTemplate(title="Test Report"))
        )

    def test_generate_with_text(self):
        template = ReportTemplate(
            elements=[
                {"type": "text", "content": "Hello World", "font_size": 14},
                {"type": "text", "content": "Second paragraph", "font_style": "I"},
                {"type": "spacer", "height": 10},
                {"type": "text", "content": "After spacer", "align": "C"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_generate_with_table(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "table",
                    "headers": ["Name", "Age", "City"],
                    "rows": [["Alice", "30", "Paris"], ["Bob", "25", "London"]],
                    "header_bg_color": [41, 128, 185],
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_table_with_column_aligns(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "table",
                    "headers": ["Name", "Score", "Amount"],
                    "rows": [["Alice", "95", "1,500 €"]],
                    "column_aligns": ["L", "C", "R"],
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_generate_with_large_table(self):
        rows = [[f"Item {i}", f"Value {i}", f"Desc {i}"] for i in range(100)]
        template = ReportTemplate(
            elements=[
                {
                    "type": "table",
                    "headers": ["Item", "Value", "Description"],
                    "rows": rows,
                    "max_rows_per_page": 25,
                },
            ],
        )
        pdf = self.engine.generate(template)
        self._assert_valid_pdf(pdf)
        assert len(pdf) > 2000

    def test_section_title_and_key_value(self):
        template = ReportTemplate(
            elements=[
                {"type": "section_title", "text": "Section I"},
                {"type": "key_value", "pairs": [["Key", "Value"]]},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_header_and_footer(self):
        template = ReportTemplate(
            header=HeaderConfig(
                lines=[HeaderLine(text="My Company", font_size=16, bold=True)],
            ),
            footer=FooterConfig(left_text="Generated by KSB-Report"),
            elements=[{"type": "text", "content": "Content"}],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_generate_to_file(self, tmp_path):
        output = str(tmp_path / "test_output.pdf")
        result = self.engine.generate_to_file(ReportTemplate(title="File Test"), output)
        assert result == output
        with open(output, "rb") as f:
            self._assert_valid_pdf(f.read())

    # =========================================================================
    # New element types
    # =========================================================================
    def test_page_break(self):
        template = ReportTemplate(
            elements=[
                {"type": "text", "content": "Page 1"},
                {"type": "page_break"},
                {"type": "text", "content": "Page 2"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_separator(self):
        template = ReportTemplate(
            elements=[
                {"type": "text", "content": "Before"},
                {"type": "separator", "color": [255, 0, 0], "thickness": 1.0},
                {"type": "text", "content": "After"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_separator_partial_width(self):
        template = ReportTemplate(
            elements=[
                {"type": "separator", "width_percent": 50},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_list_bullet(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "list",
                    "items": ["Premier point", "Deuxième point", "Troisième point"],
                    "list_style": "bullet",
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_list_numbered(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "list",
                    "items": ["Step one", "Step two"],
                    "list_style": "numbered",
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_list_dash(self):
        template = ReportTemplate(
            elements=[
                {"type": "list", "items": ["A", "B"], "list_style": "dash"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_box(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "box",
                    "border_color": [0, 0, 0],
                    "bg_color": [255, 255, 230],
                    "padding": 5,
                    "elements": [
                        {
                            "type": "text",
                            "content": "Inside the box",
                            "font_style": "B",
                        },
                    ],
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_columns(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "columns",
                    "columns": [
                        {
                            "width": 50,
                            "elements": [
                                {"type": "section_title", "text": "Left Column"},
                                {"type": "text", "content": "Left content"},
                            ],
                        },
                        {
                            "width": 50,
                            "elements": [
                                {"type": "section_title", "text": "Right Column"},
                                {"type": "text", "content": "Right content"},
                            ],
                        },
                    ],
                    "gap": 10,
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_columns_three(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "columns",
                    "columns": [
                        {"width": 33, "elements": [{"type": "text", "content": "A"}]},
                        {"width": 33, "elements": [{"type": "text", "content": "B"}]},
                        {"width": 33, "elements": [{"type": "text", "content": "C"}]},
                    ],
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_qrcode(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "qrcode",
                    "data": "https://ksb.bj/report/2026-001",
                    "size": 25,
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_signature_block(self):
        template = ReportTemplate(
            elements=[
                {
                    "type": "signature_block",
                    "signatures": [
                        {"label": "Le Directeur", "name": "M. DUPONT", "title": "DG"},
                        {"label": "Le Comptable", "name": "Mme. MARTIN"},
                    ],
                },
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    # =========================================================================
    # Variables
    # =========================================================================
    def test_variables_builtin(self):
        template = ReportTemplate(
            elements=[
                {"type": "text", "content": "Date: {{current_date}}"},
                {"type": "text", "content": "Year: {{year}}"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_variables_custom(self):
        template = ReportTemplate(
            variables={"company": "KSB Tech", "ref": "RPT-001"},
            elements=[
                {"type": "text", "content": "Company: {{company}} — Ref: {{ref}}"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    # =========================================================================
    # Watermark
    # =========================================================================
    def test_watermark(self):
        template = ReportTemplate(
            watermark=WatermarkConfig(text="BROUILLON", color=(220, 220, 220)),
            elements=[{"type": "text", "content": "Content under watermark"}],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    def test_watermark_with_page_break(self):
        template = ReportTemplate(
            watermark={"text": "CONFIDENTIEL"},
            elements=[
                {"type": "text", "content": "Page 1"},
                {"type": "page_break"},
                {"type": "text", "content": "Page 2"},
            ],
        )
        self._assert_valid_pdf(self.engine.generate(template))

    # =========================================================================
    # Invoice template
    # =========================================================================
    def test_invoice_template(self):
        template = invoice_template(
            company_name="KSB Tech",
            invoice_number="2026-001",
            client_name="Jean Dupont",
            items=[
                {"description": "Widget A", "quantity": 2, "unit_price": 15.00},
                {"description": "Service B", "quantity": 1, "unit_price": 50.00},
            ],
            tax_rate=0.18,
        )
        assert template.title == "FACTURE 2026-001"
        pdf = self.engine.generate(template)
        self._assert_valid_pdf(pdf)
        assert len(pdf) > 1000

    # =========================================================================
    # Mixed content
    # =========================================================================
    def test_mixed_all_elements(self):
        """Report using every element type at once."""
        template = ReportTemplate(
            title="Full Demo Report",
            watermark={"text": "DRAFT"},
            variables={"author": "Test Author"},
            header=HeaderConfig(
                lines=[HeaderLine(text="Test Corp", font_size=14, bold=True)],
            ),
            footer=FooterConfig(left_text="Footer — {{author}}"),
            elements=[
                {"type": "text", "content": "By {{author}}"},
                {"type": "separator"},
                {"type": "section_title", "text": "Section A"},
                {
                    "type": "list",
                    "items": ["Point 1", "Point 2"],
                    "list_style": "bullet",
                },
                {"type": "key_value", "pairs": [["Key", "Val"]]},
                {"type": "spacer", "height": 5},
                {
                    "type": "columns",
                    "columns": [
                        {"width": 50, "elements": [{"type": "text", "content": "L"}]},
                        {"width": 50, "elements": [{"type": "text", "content": "R"}]},
                    ],
                },
                {
                    "type": "table",
                    "headers": ["A", "B"],
                    "rows": [["1", "2"]],
                    "column_aligns": ["L", "R"],
                },
                {
                    "type": "box",
                    "elements": [{"type": "text", "content": "Boxed"}],
                },
                {"type": "qrcode", "data": "https://test.com"},
                {"type": "page_break"},
                {
                    "type": "signature_block",
                    "signatures": [
                        {"label": "Signed", "name": "John"},
                    ],
                },
            ],
        )
        pdf = self.engine.generate(template)
        self._assert_valid_pdf(pdf)
        assert len(pdf) > 2000
